### ISSUE TITLE
pip install numpy issue

### ISSUE THREAD

**Issue by mkhorton** [connorourke/crystal_torture#3]
Just a small note: because you use numpy in the setup.py `pip install crystal_torture` will not work in a clean virtual environment (ie without numpy already pre-installed); it might be worth making a note of this in the readme. This can also cause problems were crystal_torture to be listed in the requirements.txt of another package.

**Comment by mkhorton** [comment]
(I'm not sure if this is related to the other open issue when I saw mentioned that a pip install does work in a clean venv. My example of this *not working* is with Python 3.7.0 and pip 10.0.1 and also pip 19.0.3).

**Comment by bjmorgan** [comment]
This should be fixed in commit https://github.com/connorourke/crystal_torture/commit/10ae09a65a7d9641cd30f161315720f52252b46d.
