### ISSUE TITLE
Missing function call in `to_unit_cell` causing test failures

### ISSUE THREAD

**Issue by mkhorton** [connorourke/crystal_torture#4]
`to_unit_cell` is a method and should be `to_unit_cell()`: 

https://github.com/connorourke/crystal_torture/blob/18b2e52d31d0e520b4226754fcee3322e39af118/crystal_torture/pymatgen_interface.py#L271

There are a few other lines like this also.

**Comment by mkhorton** [comment]
(An equivalent way to write this would be `Structure.from_sites(sites, to_unit_cell=True)`.)

**Comment by bjmorgan** [comment]
Pull request https://github.com/connorourke/crystal_torture/pull/6 fixes these test errors by replacing the offending code with:
```
for site in structure.sites:
       site.to_unit_cell(in_place=True)
```

**Comment by mkhorton** [comment]
Great, thank you! Yes it seems strange to me also, as far as I can tell from looking at the pymatgen git history `to_unit_cell` has been a method for a long time, but I assume this worked previously.

**Comment by bjmorgan** [comment]
Weirdly, this recent commit as part of pymatgen v2019.3.13 replaces a bunch of `site.to_unit_cell` examples: https://github.com/materialsproject/pymatgen/commit/d3702a357b8c113701cd9e98406a001a10d5537a

**Comment by mkhorton** [comment]
Ah, yeah. There was some discussion recently about "property abuse", i.e. a few places where something was a property where it would make more sense for it to be a method. Generally pymatgen tries not to break backwards compatibility but this might be the exception.
